sudo: required
services:
    - docker

before_install:
    - docker build -t vishalbendre/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vishalbendre/docker-react npm run test -- --coverage--       